@startuml

title __RENTPACKAGE's Class Diagram__\n

  namespace com.example.airpnp {
    namespace RentPackage {
      class com.example.airpnp.RentPackage.RentActivity {
          ~ autocompleteSupportFragment : AutocompleteSupportFragment
          ~ dayCheckBoxView : View
          ~ edName : EditText
          ~ fridayTV : TextView
          ~ fridayTime : TextView
          ~ mondayTV : TextView
          ~ mondayTime : TextView
          ~ nextStep : Button
          ~ priceLayout : EditText
          ~ saturdayTV : TextView
          ~ saturdayTime : TextView
          ~ sizeItems : ArrayList<SizeItem>
          ~ sizePosition : int
          ~ sizeSpinner : Spinner
          ~ sundayTV : TextView
          ~ sundayTime : TextView
          ~ thursdayTV : TextView
          ~ thursdayTime : TextView
          ~ timeLayout : EditText
          ~ tuesdayTV : TextView
          ~ tuesdayTime : TextView
          ~ wednesdayTV : TextView
          ~ wednesdayTime : TextView
          {static} - API_KEY : String
          - address : String
          - city : String
          - stPrice : String
          + onCreateView()
          - createParkingSpace()
          - inputCheck()
          - onCheckBoxClicked()
          - onDayCheckBoxClicked()
      }
    }
  }
  

  com.example.airpnp.RentPackage.RentActivity o-- com.example.airpnp.Helper.FirebaseHelper : firebaseHelper
  com.example.airpnp.RentPackage.RentActivity o-- com.example.airpnp.LocationPackage.LocationControl : locationControl
  com.example.airpnp.RentPackage.RentActivity o-- com.example.airpnp.UserPackage.ParkingSpaceControl : parkingSpaceControl


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
